const liste = ["Herr Salahshoor Ahmad Saeed" , "Herr QAYED ABDUL QAYOOM" , "Herr SAAED Sayed Mohammad Seddiq" , "Faru Haqjoo Rahila" , "Herr HEMMAT SULAIMAN" 
,"Herr Salahshoor Ahmad Saeed"
,"Herr QAYED ABDUL QAYOOM"
,"Herr SAAED Sayed Mohammad Seddiq"
,"Faru Haqjoo Rahila"
,"Herr HEMMAT SULAIMAN"
,"Herr MUSLIMYAR ABDUL KHALIQ"
,"Frau HOSSAINI SHABNAM"
,"Herr Khairkhah Mohammad Edris"
,"Herr Azad Abdul Satar"
,"Frau DANESHYAR MARYAM"
,"Herr Jawad Mohammadi"
,"Herr YOUSSOFI RAMIN JAMI"
,"Herr Saiyar Mohammad Kabir"
,"Herr MOHAMMAD RAFI ATAIE"
,"Herr Aziz Ahmad Khinjani"
,"Herr Edris Naseri"
,"Frau Sadat Hossini Narges"
,"Herr Shirazi Lutfu Rahman"
,"Herr Arian Farid Ahmad"
,"Herr Motahari Bahram"
,"Herr AHMADZAI SAFIULLAH"
,"Herr Saleh Abdul Rahman"
,"Frau Shekofa Ghoury"
,"Frau Zaland Sharifa"
,"Herr Sarwari Mohammad Saeed"
,"Frau Masoumah Rahmany"
,"Herr Abbas yousufi"
,"Herr BEHZAD ABDUL WASE"
,"Herr Mohammad Jawad Bayat"
,"Herr Tamanna Abdul Hakim"
,"Herr Shafiq Ehsan Ahmad"
,"Frau OMARI NAJIA"
,"Herr YAZDAN PANAH HESHMATULLAH"
,"Faru RAHMATI MINA"
,"Faru MOKHLES MASUMA"
,"Frau Mohammadi Fatima"
,"Faru NOORI MARIA"
,"Frau AHMADI RUQIA NAMA"
,"Herr Abdul Qodus"
,"Herr SHAYAGAN HUSSAINDAD"
,"Herr SOROUSH MOHAMMAD MAHDI"
,"Herr Moshtaq Abdulah"
,"Herr Hashimi Sayed Mohammad Raza"
,"Herr ALIZADA Sultan"
,"Herr Ali Amiri"
,"Herr Hujjatullah Qazizada"
,"Herr Yusuf hamidi"
,"Herr OMAR MOHAMMAD RAFI"
,"Frau Najia Haidar Kohistani"
,"Frau AKBARI MARZIYAH NAMA"
,"Frau Fatema Ghairat"
,"Frau FAEQEH ALIZADEH"
,"Herr Nezami Shujauddin"
,"Frau N oo ri Arezoo"
,"Herr Habib Hayatullah"
,"Frau Jami Naaemah"
,"Herr FARHAD MASIHLLAH"
,"Herr Nazir Ahmad Noori"
,"Frau AMINI ZAHRA"
,"Herr Arabzada Abdul qadir"
,"Herr WAHEDI SAYED MAHFOOZ"
,"Herr Habib Rasa Mohammad Yusof"
,"Herr SAYED ANWAR SIRAT"
,"Herr Behnam Mahboob"
,"Frau Zuhal malikzada"
,"Frau Sana Negina"
,"Herr KHADEM FAZLLOLRAHMAN"
,"Frau Haqjoo Monira"
,"Herr Fahim Sharifi"
,"Herr MANSOURI SAYED AHMAD SABER"
,"Herr BAQIRIYAN MOHAMMAD"
,"Frau JAFARI MASOUMAH"
,"Herr OSMANI NAJMUDDIN"
,"Frau Hamedi Taiebe"
,"Herr BAHA BAHRAM"
,"Herr Ahmad Bahir Nosrat"
,"Herr Zaki Mohammad zaki"
,"Herr LANGARI SAYED ABUDIN"
,"Frau KHAJA ZADA NAHID"
,"Herr SARAJ AHMAD JAHED"
,"Herr Abdul Raqib"
,"Herr Mohammad Mubeen Ak hundzada"
,"Herr SAMIMI MURTAZA"
,"Frau Nahid Zia"
,"Herr BAHER NEMATULLAH"
,"Frau Qarizada Farkhonda"
,"Herr HASANZADA ABDUL SABOUR"
,"Frau HAIDARI BAHAR"
,"Herr Qazaizada Abdul Zaher"
,"Herr Mohammad Naim Panah"
,"Herr Ahmadullah Afzali"
,"Frau JOYA TAYEBAH"
,"Herr Qais Malikzada"
,"Herr NABIL NAJIB"
,"Frau Mastour Qodsya"
,"Faru Haqjoo Nooshafarin"
,"Herr SHOAIB FRUTAN"
,"Herr Ahmadi Mohammad Sharif"
,"Herr Qani Haji Zabiullah"
,"Herr Rameen Sulaimankhail"
,"Herr Rahimi Farzad"
,"Frau KHAJAZADA PARWANA"
,"Herr Nazir Ahmad Dehgan"
,"Herr Hasbi Ghulam Maruf"
,"Herr HABIBZADA GHULAM RASOUL"
,"Herr Sarwari Mohammad Saeed"
,"Herr Asadullah SayeedKhailee"
,"Herr Ahmad Wais Basiri"
,"Herr Amiri Safiullah"
,"Herr Zerak Syed Shakeeb"
,"Herr Anwarullah Anwari"
,"Frau Qattali Rabea"
,"Herr Abdul Waheed Ahmadi"
,"Herr Shafi Aamini"
,"Herr DANISH MASOUD JAN"
,"Frau Nickzad BiBi Sajeda"
,"Herr Mahmoodi Sayed Kabir"
,"Herr Assaddullah Obehwal"
,"Herr Ehsan Naveed"
,"Herr Atiqullah Noorzad"
,"Herr WAHEDI Mohammadullah"
,"Herr REJA,Matiullah"
,"Frau Karimian Fariba"
,"Frau FAZELZADA LAYA"
,"Herr Hosain jan Yosofy"
,"Herr Mohammad Yusuf Azizi"
,"Herr Faeqa Alizadeh"
,"Herr Ramin Farzan"
,"Herr Mohammad Yusuf Azizi"
,"Frau Sarwari Lailima"
,"Heer SUROSH SAYED AHAD"
,"Herr Qasemi Sayed Delaqa"
,"Frau Safa Anita"
,"Frau Sharyar Nadiya"
,"Herr OSMANI MAHMOUD"
,"Frau MAJIDY Nazanin"
,"Frau MAJIDY Hasina"
,"Frau SHERZADS hakeba"
,"Herr Saleh Abdul Rahman"
,"Herr KARGAR GHULAM SARWAR"
,"Herr SHINDANDI ABDUL JAMIL"
,"Herr Jami Azizurahman"
,"Frau ANWARI Nahid"
,"Herr Khaze Ghulam Naser"
,"Herr Ahmad Khalil Ghamai"
,"Herr Mohammad Haroon Naimi"
,"Herr Gulistani Mohammad Ewaz"
,"Herr POYESH MOHAMMAD OMAR"
,"Herr Basir Ahmad Noori"
,"Herr Saboori Abdul Ghafoor"
,"Herr ABED ABDUL RAHIM"
,"Herr Khatibi Vahid"
,"Herr MOSAVI SAID MOHMMAD TAQI"
,"Herr Mateen Abdul Qaher"
,"Herr TEMORI MOHAMMAD ALI"
,"Herr Khoshdel Elyas"
,"Herr Qurbanzada Hashmatullah"
,"Herr Masihullah Ghalib"
,"Frau Omid Hamida"
,"Fräulein Mohammadi Arefa"
,"Herr Arian Nazamuddin"
,"Herr Mohammadi Wali Mohammad"
,"Frau RASOULI PARWANA"
,"Herr Raheen Abdul Rahim"
,"Herr FETRAT ZABIHULLAH"
,"Herr Azimi Ahmad Belal"
,"Frau Raheen Saleha"
,"Frau Nesar Zainab"
,"Herr AZIZI Atawollah"
,"Frau Nesar torpikai"
,"Heer Hamidy Baryalai"
,"Herr Abdul Rasoul Yaqoobi"
,"Herr Basir Ahmad Noori"
,"Herr NZARI Shahram"
,"Frau Habib Farishta"
,"Herr Jahani Hamed"
,"Herr Ibrahimi Shamsurahman"
,"Herr Hamedi Sa. Mohammad Saeed"
,"Herr ENAYAT,ENAYATULLAH"
,"Herr QURAISHI SAMIULLAH"
,"Herr Mohammadi Jawid"
,"Herr Taeb Abdul Tawab"
,"Frau Akhgar Somaya"
,"Herr Shabir Ahmad Mubasher"
,"Herr Munir Ahmad Ahmadi"
,"Frau Hashem Banafsha"
,"Frau JOYAN SOMAYAH"
,"Herr JOYA HASHMATULLAH"
,"Frau RAHMATI PARISA"
,"Frau sedeqi nabizadah Masumah"
,"Frau Shakila Azizi"
,"Herr Sirat Rahmatullah"
,"Herr MOHAMMADI ABULRAHIM"
,"Frau Mursal Rasuli"
,"Herr Ayubi Abdul Rahman"
,"Herr AZIMI FAZAL AHMAD"
,"Frau Ahmadi Narges"
,"Frau Aziza ZABIHI"
,"Frau Mohammadi Soraya"
,"Herr Morwat Ahmad shah"
,"Herr Matiullah Salehi"
,"Frau Anwari Sonita"
,"Frau Parwin Sharifi"
,"Herr Tamanna Abdul Hakim"
,"Herr Qasemi Mohammad Hadi"
,"Frau Qasemi Atefeh"
,"Frau Tahiri Sameya"
,"Herr Mohammad Amin Farhange"
,"Herr Eman Abdul Wahed"
,"Herr Mohammad Ebrahim"
,"Herr Hashemzada Fayegh"
,"Frau Qurbanzadeh Asma"
,"Frau Darwish Lema"
,"Herr FARDOST REZA"
,"Frau Hashemzade Parwin"
,"Frau Fatema Turkani"
,"Faru RASHIDI ZAINAB"
,"Frau Hashemzadeh Simin"
,"Frau Hashem Zadeh Shahin"
,"Frau Mohseni Horia"
,"Herr ABRAHIMI GHADIR"
,"Frau Shakila Azizi"
,"Herr SKANDARY AHMAD SADIQ"
,"Herr JOYA AHMAD SHOAIB"
,"Herr Sabruddin pahlawe"
,"Fr au Sadaat Rabeha"
,"Frau HABIBI NASRIN"
,"Frau SALEEM Saira"
,"Herr HABIBI NEMATULLAH"
,"Herr Zalmay Hamidi"
,"Frau Sarah frouhar Rasooli"
,"Herr Radmal Ahmad Sohail"
,"Herr ABDUL AZIM AMIRI"
,"Frau Noori Maria"
,"Herr Sarwari Ahmad zia"
,"Frau Alipur Marjan"
,"Frau Sharifi Soh"
,"Frau Fatima Batory"
,"Frau Raheen Basira"
,"Frau Tawasoly Masoma"
,"Frau Hamidi Laya"
,"Herr FAIZI Masood"
,"Frau MAJIDI ELHAM"
,"Frau Baqaie Rohina"
,"Herr Sayedi Yama"
,"Herr Saljuqie Mohammad Ehsan"
,"Herr SAMIULLAH AMINY"
,"Frau AZIZI HABIBA"
,"Herr HANIF BASHIR AHMAD"
,"Herr SADAT SAYED HASIB"
,"Herr Farahi noor Ahmad"
,"Herr AHMADI ABDUL NASER"
,"Herr KHAIRKHAH Mohammad Gul"
,"HERR MOHAMMADI JAWED"
,"Herr Sadat Sayed Hamed"
,"Herr VASEGH GHADER ALI"
,"Herr Mohammad Zia Forogh"
,"HERR FATIH AHMAD FARID- FAMILY"
,"Herr Rasem Arian"
,"Herr Khawary Mohammad Reza"
,"Herr Fazl Ahmad Sarwari"
,"Frau HASSANI Fatema"
,"Frau Nabizada khadija"
,"Faru MOKHLES MASSUMA"
,"Frau HUSSAINI MAHBOBA"
,"Frau AMIRI MONESA"
,"Frau Fayegha Turkani"
,"Herr NAZARI Abdul Hamid"
,"Heer Ahmadi Wase"
,"Herr Aiar Abdul alim"
,"Herr Abbasi Azizurahman"
,"Herr HABIBI AHMAD"
,"Herr HABIBI HAMIDULLAH"
,"Frau Kakar Shiva"
,"Herr Abdul Ahmad Yaqobi"
,"Herr Mohammadi Mirwais"
,"Herr Shirzadi Said Abdul Rahim"
,"Herr HASHEMI Sayed Hamid"
,"Herr WEHEDI Mohammadullah"
,"Frau JAKANI KHATERA"
,"Frau Waziri Wida"
,"Herr FAROOQI GHULAM HABIB"
,"Herr Radmal Ahmad Sohail"
,"Herr Noman Moheb Rahmani"
,"Herr FATTAHI FARSHAD"
,"Herr Behnam Mahboob"
,"Herr Tareq Qassemi"
,"Herr Majidi Abdul Naser"
,"Herr NOORI HAFIZULLAH"
,"Herr Rashed Lutfullah"
,"Herr Darman Azizollah"
,"Herr Sayed Abdul Hamid Razavi"
,"Frau Mohammadi Jamila"
,"Frau Gul sima shirzai"
,"Herr Abdul Qadir Samadyar"
,"Herr Alkozay Edress"
,"Herr SALEHY SAYED JAMAL"
,"Frau Faqiri Fahima"
,"Herr OMARYAR HAMIDULLAH"
,"Frau Yousofi Sohailla"
,"Herr Shafiq Rohullah"
,"Herr Nowrozi Mohammad"
,"Frau Nowrozi zakira"
,"Herr NEAMAT NEAMATULLAH"
,"Herr MERZAPOOR Naqibullah"
,"Frau Hussaini Sharan Razia"
,"Frau Mohammadi Pari Gol"
,"Frau ARIAN NAJEBA"
,"Frau Fatima Jafari"
,"Herr KARIMI NAWEED AHMAD"
,"Frau Khaleqi Elaha"
,"Herr NAJEEBULLAH ARASH"
,"Frau Mahmoodi Negina"
,"Herr Mohmmad Rafi Khairkhah"
,"Herr Parwiz sapai"
,"Herr KHALILI ABDUL BARI"
,"Herr Ahmad Safdari"
,"Herr HIMAT ZIKRIA"
,"Herr Habibi mohammad ghows"
,"Herr ZAKI Mohammad"
,"Frau Yusufi Maryam"
,"Herr Komroz Parwiz"
,"Frau AZAMI KHADIJA"
,"Herr SHAFAQ MOHAMMAD YONUS"
,"Herr Khawari Abdul Sami"
,"Herr Hasrat Mohammad Arif"
,"Herr Aslami Maqsoud"
,"Herr GULZADA MOHAMMAD ASLAM"
,"Herr Hashimi Sayed Azim"
,"HERR ISTALIFI GHULAM RASOUL"
,"Herr Hoshmand Abdul Hakim"
,"Herr Shirzady Sayed Mohammad"
,"Herr Moshtaq Nematullah"
,"Herr Mobarez abdul Tawab"
,"Frau Akeed Mozhda"
,"Herr ERFANI Mohammad kazim"
,"Frau Laleh Raufi Khairkhah"
,"Herr AASHNA ABDULL AZIZ"
,"Frau Yousufzai Samira"
,"Herr Yousufzai Farzad"
,"Herr RAHMANI KHAIRUDDIN"
,"HERR KARIMI MASOUD"
,"Faru Noori Nazanin"
,"Herr Danishyar Naweedullah"
,"Herr Hamid Hayatullah"
,"Herr Amiri Mushfiq hussain"
,"Herr AMINI SHAFI"
,"Frau Azimi Hafiza"
,"Frau Karokhi Rozita"
,"Herr Joyan Wais"
,"Herr Noori Muhammad Danish"
,"Herr HABIBI NAWIDULLAH"
,"Herr AMIRI ABDUL AZIM"
,"Herr Mahajer Ahmad"
,"Herr jazim wahid"
,"Herr Hakimi Mohammad Ashaq"
,"Frau Taheri Elaha"
,"Herr SHİRZADİ FAİZULHAQ"
,"Frau MOHSENIFAKHIRA"
,"Herr Mousavi Sayed Mohsen"
,"Herr NOORI FAISAL"
,"Frau Mohammadi Masuma"
,"Herr Habibi Rahiq"
,"Frau DOLATY NAJLA"
,"Herr Arab Salim Mohammad"
,"Herr Quraishi Yaqub"
,"Herr AKHI MOHAMMAD NASER"
,"Herr FARHANGE MOHAMMAD AMIN"
,"Frau ALIZADAH ATEFA"
,"Herr Halimie Abdul Azim"
,"Herr Azizi Aziz Ahmad"
,"Herr Muzamil Mohammad"
,"Herr Mohammad Kabir"
,"Herr Haqjoo Edris"
,"Frau Yalda Wahdat"
,"Herr Khalid Karimi"
,"Herr Shirzadi Saidnoorollah"
,"Frau Qazizada Nilofar"
,"Frau SARA FAZILI"
,"Frau Frouhar SHIRDEL"
,"Herr TEMORI MOHAMMAD ALI"
,"Frau Freshta azami"
,"Herr Miri Mir Mohammad Wais"
,"Herr AMIRI ABDUL KHALIQ"
,"Herr Qeumars Fardin"
,"Herr Arabzadeh M ohammad"
,"Frau Wafa Mohammadi Farzana"
,"Frau Bibi GUL Ahadi"
,"Frau Dr PARISA AMIRI"
,"Herr Z IA FIROOZ AHMAD"
,"Herr ANWARI OBAIDULLAH"
,"Herr RASHEDI ALI"
,"HEER Muhammad Wahed zahiry"
,"Herr Rezai Arif"
,"Herr HABIBI BARKATULLAH"
,"Herr HALIMI ZABIHULLAH"
,"Herr Rouhullah Yosofi"
,"Frau Basirat Marzia"
,"Frau AHMADZAI RANGINA"
,"Herr MAHDAWI ARZI HUSSAIN"
,"Herr Poyesh omar"
,"Herr Baburi Mohammad Paiman"
,"FRAU AKBARI NILOFAR"
,"Herr Azimi Arian Fahima"
,"Frau RASOOLI MASOMA"
,"Herr Rahmati Wahid"
,"Herr KHAIRKHAH Mohammad Gul"
,"Herr Miri Sayed Ahmad Shah"
,"Herr Atlas Mohammad Hussain"
,"Herr Mohammadi Mahdi"
,"Herr Nasimi Masoud"
,"Herr Arain Bahauddin"
,"Herr Qana Shamail"
,"Frau Alipour Mitra"
,"Frau Shareq Lida"
,"Frau Fahim Farishta"
,"Frau Mohammadi Marzia"
,"Herr Hamidi Qudratullah"
,"Herr Shirzadi Saidnoorollah"
,"Frau Rahmati Nahid"
,"Herr Farahi Habibullah"
,"Frau Adineh Qazizadeh"
,"Frau Hosna Panah"
,"Frau Faghiry Haideh"
,"Herr Abdull Rahman Samim"
,"Herr Karimi Hamed"
,"Herr Kamali Said Abdul Qayoum"
,"Herr Said Faisal Rahmani"
,"Frau Fatema SAMIM"
,"Herr DAWOODZOI AHMAD YAMA"
,"Herr Jalali Mohammad Aref"
,"Frau SOROOSH WAHIDEH"
,"Frau HUSSAINZADA ROYA"
,"Herr Mohammad Omar Samim"
,"Frau Hekmatullah Hekmat"
,"Frau Chakari Yousufzai Humaira"
,"Herr Kakar Zahoraddin"
,"Herr Sarwari Mohammad Saeed"
,"Herr JUNBESH HAMIDULLAH"
,"Herr Mohammad Salim Esmaeli"
,"Herr Rashed Sarwari"
,"Herr Rateb Hariwa"
,"Herr Anis Mohammad khan"
,"Herr Kakar Faridadin"
,"Herr AKBARY ABDULRAHIM"
,"Herr Ramin Farzan"
,"Herr ZAHID Sayed Abdul Karim"
,"Herr Firoozeh Rahmani"
,"Herr AMIRI, FARAIDOUN"
,"Herr Rezai Mohammad Qasem"
,"Herr HOSAINI FAROOQ"
,"Herr KAZIMI ABDUL GHANI"
,"Herr Sadat Said Aqa"
,"Herr Hamidi Iraj"
,"Frau AZAMI KHATERA"
,"Frau JAMI FARIBA"
,"Herr Haidari Ishaq"
,"Frau BI BI Farokh Rahmani"
,"Herr KAZEMI MOHAMMAD TAQI"
,"Herr Ehrari Mohammad Shafi"
,"Herr KHAIRKHAH Mohammad Gul"
,"Herr EMRAAN KAZEM"
,"Herr Razavi sayed Abdul Hamid"
,"Herr Abdulmanan Qazikhani"
,"Herr VAEZI MOHAMMAD AREF"
,"Frau OBAIDI SOSAN"
,"Herr DADKHAH MOHAMMAD TARIQ"
,"Frau NOORI SOHAILA"
,"Herr Azad Abdul Satar"
,"Frau Baburi Maria"
,"Frau Mevr. UMULBANIN KHAVARY"
,"Herr Qasemi Sayed Delaqa"
,"Herr Mirwais Akhtari"
,"Herr ZAKARIA RADMANESH"
,"Herr Ghulam Reza Mehsa"
,"Herr ASIF AKBARI"
,"Herr ABDUL BARI KHALILI"
,"Herr AHMAD JAWAD HIMMATY"
,"Frau Bashardost Beheshta"
,"Herr MUMTAZUDDIN HANIFI"
,"Frau Yousofi Anisa"
,"Herr Arsalan Hamidi"
,"Frau Darwish Roya"
,"Frau Darwish Nabila"
,"FRAU HAMEDI HABIBA"
,"Herr TAJDAR SAYED ALI KHOSROW"
,"Herr DELIR MOHAMMAD TAQI"
,"Faru TAHERI ELAHA"
,"Herr OSMANI HAFIZULLAH"
,"Herr Hariva Noor Aqa"
,"Herr Joyan Wais"
,"Herr VAEZI MOHAMMAD ZUBAIR"
,"Frau TAHERI FATEMAH"
,"Frau SABRI SOHAILA"
,"Herr Alam Ghulam Mostafa"
,"Herr ALMAS GULAHMAD"
,"Frau MAHMODY HAKIMA"
,"Herr Mohammadi Mubarez"
,"Herr NADEEM SADAT Sayed Ezatullah"
,"Frau SAJADI ZAKYA"
,"Herr DELIR MOHAMMAD TAQI"
,"Herr Safi Abdul Wasi"
,"Her Mohammad Rahim Osmani"
,"Herr SAGHARY FARHAD"
,"Herr ELYAS MOHAMMAD YASIR"
,"Herr Mohammad Edris Khairkhah"
,"Herr Mohammadi Jawid"
,"Herr ASKARZADA EZZATULLAH"
,"Frau Maryam Rezae"
,"Herr Khavari Murtaza"
,"Herr TEMORI MOHAMMAD ALI"
,"Herr Hazeem Shafiqullah"
,"Frau Qazizadeh MEHRAL"
,"Frau Sahim Hamid Sokofa"
,"Frau Aimaq Roshan"
,"Faru NOORI MARIA"
,"Herr Rahimi Adul Hamid"
,"Herr MOHAMMADI HUSSAIN DAD"
,"Herr Poya Mohammad Hassan"
,"Frau Azadani Hamidah"
,"Frau Wahedi Nilab"
,"Herr Nadim Sayed Mohammad"
,"Frau ASKARI NARGES"
,"Heer Maruf Ataiye"
,"Herr Jahed Asadullah"
,"Herr Esmatullah Esmat"
,"Frau Alia Shams"
,"Herr Dr.Baqir Rezai"
,"Herr Sadiqi Mohammad Taqi"
,"Herr Hayatullah RAHMANI"
,"Herr Muhammad Asif"
,"Frau Rohina"
,"Herr Frotan Mahboob Shah"
,"Herr Mohammad yusuf"
,"Frau Faqirzada Sowaila"
,"Herr Habibi Jamal Abdul Naser"
,"Herr Moqeem Ahmad Moneer"
,"Frau Arezo,Rasooli"
,"Herr ZAINAL WAZIR AHMAD"
,"Herr Waiezi Mohammad"
,"Herr shirzad Mukhtar"
,"Herr Shirzad Faisal"
,"Herr NADIM SAYED MOHAMMAD"
,"Herr Moqeem Ghulam Jelani"
,"Herr MOHAMMADI HAMIDULLAH"
,"Herr mansoori Ramin"
,"HERR KHATIBY AHMAD"
,"Herr Khairkhah Mohammad Edris"
,"Herr JOOYAN MOHAMMAD ALI"
,"Herr Jawadi Ali"
,"herr JAWAD YOUSEFI"
,"Herr Hossainy Sayed Rahim"
,"Herr Hamidi Qudratullah"
,"Herr Sakhizada Reshad Ahmad"
,"Herr Haidari firooz Ahmad"
,"Frue ARBABZADEH ASILA"
,"Frau, Fazly Sohaiba Nama"
,"Herr Wahidullah Attayee"
,"Frau Sadiqa Samim"
,"Frau Rahmati Mastoora"
,"Frau Frishta khalili"
,"Faru MOKHLES MALEKA"
,"Frau AHMADI Sonia"
,"Frau freshta azghari"
,"Frau baheshta shaheen"
,"Frau TAHERI FATEMAH"
,"Frau afsana habib zada"
,"Frau AZAMI ARAZO"
,"FRAU HABIB FARZANA"
,"Frau Mahmoodzada Maleka"
,"Frau Nazarian Tayebeh"
,"Herr Fekrat Farhad"
,"Herr Gh. Farooq Farhad Salehyar"
,"Frau NOORI SOHAILA"
,"Frau PANAHI RAHILA"
,"Frau Rahimi Azada"
,"Frau Shabana Seddiqi"
,"Frau Shabnam nama Karimi"
,"Frau Weeda Omare"
,"Herr AHMAD NAWEED OSMANI"
,"Herr Hemmat Mohammad Mustafa"
,"Herr KHOURDAD GHAFOORYAR ABDUL BARY"
,"Herr Mohammad Ershad Alokozay"
,"Herr Mojtaba Yosefi"
,"Herr Mozaffari Ali juma"
,"Herr NAJIBA FETRAT"
,"Herr Najibullah Ahadi"
,"Herr Nazir Ahmad MODARESS"
,"Herr Rabiullah Faizi"
,"Herr Saleh Abdul Rahman"
,"Herr Sidiqi Mohammad Taufiq"
,"Frau zahra sadeqi"
,"Herr Ali Afshar"
,"Frau RAHMATI KATOZI NOORIA"
,"FRAU SAEEDI MARZIA"
,"Herr Hasibullah Khadem"
,"Frau Khatima Salehi"
,"Herr Shafiqullah Tahery"
,"Herr Mohammad Qasem Rezai"
,"Herr SAYED SHAKEEB ZERAK"
,"Herr Mohammad Nasim"
,"Herr MUSAVI SAYED EHSAN"
,"Herr HAMID ARGHANDEWAL"
,"Herr Nasir Ahmad Seddiqi"
,"Herr Aqa Mohammad Sadiqi"
,"Herr Sebghatullah. Shirzadi"
,"Herr Roohullah Mohammad Nishan"
,"Herr AYAN ABDUL MATIN"
,"Frau Alizada SimaGul"
,"Herr HAMDARD ALI AKBAR"
,"Herr Hasanzadah Reza"
,"Herr Mellatyar Mohammad Ali"
,"Herr HALIMI ABDULRAHMAN"
,"Herr AHMADI ZAIDULLAH"
,"Herr. RAOUFI AHMAD FAISAL"
,"Frau Nazarian Catrin Nameh"
,"Frau Kazemi Yasaman"
,"Herr AZAMI Abdul Ramin"
,"Herr Ihsanullah Shinwari"
,"Herr Mahmoodi Mohammad Habil"
,"Herr Hashem Zada Mohammad Omid"
,"Faru Yousofi Homa"
,"Ftau Nazimi Azita"
,"Frau WAJIHA AMERI"
,"Frau Rasouli Toktam"
,"Herr NajibullahFrotan"
,"Frau Shamseya Saha"
,"Frau Farahnaz Haidari"
,"Herr Abdul Maqsood Rasooli"
,"Herr AHMAD MOKHTAR QADERI"
,"Frau Fakhria baqizadeh"
,"Herr MHAMMAD HAKIM HAKIMI"
,"Frau Maryam Ahmadi"
,"Herr Arezo,Rasooli"
,"Frau Laila yousfi"
,"Frau Khatima Salehi"
,"Herr Mohammad Ershad Alokozay"
,"Frau Shah Jahan Kabiri"
,"Frau Rita fazly Alokozay"
,"Frau Shakira Aslami"
,"Frau ataei shakiba"
,"Herr ataei danish"
,"Frau Pawrin Asady"
,"Frau SAKHA FROZAN"
,"Herr KARIMI HAMED"
,"Frau Atefa Dorani"
,"Frau Adel Elaha"
,"Frau Mahsa Babory"
,"Frau Farishta Mahmoodi"
,"Herr Razia Wahdat Atayee"
,"Herr Nabizada zia"
,"Herr SADDIQI AZIZULLAH"
,"FRAU TAJDAR AZAR"
,"Herr Burhany Ratib"
,"Herr ALAVI SAYED MOHAMMAD TAHA"
,"Herr Abdullah Sherzad"
,"Frau Shaista Safi"
,"Herr Ali Jan Asem"
,"Herr YUSOFI KAMRAN"
,"Herr said meraqa hossainin"
,"Herr khairullah Bahij"
,"Faru Ahmadi Roya"
,"Herr Rabiullah Faizi"
,"Herr MOHAMMAD SHAH TURKANI june"
,"Herr Mohammad Morteza Mohebbi"
,"Herr Mohmmad Qaboul Tokhy"
,"Frau Rahmani Mozhgan"
,"Herr Sadat Sayed Qasem"
,"Herr Ziaurhamn zahid"
,"Frua Sarwari Lilima"
,"Frau RADMANESH AREZO"
,"Herr Jahed Asadullah"
,"Herr NAZARI MOHAMMAD JAWAD"
,"Herr EBRAHEMI ZABIHULLAH"
,"Herr Turkmani Ali Reza"
,"Herr Omid Ahmady"
,"Herr Sayed Munir Sadat"
,"Herr NASER MOHAMMAD KAZIM"
,"Herr SHARIFY BISMULLAH"
,"Herr Mohammad Hasan Sediqi"
,"Frau yasamin Azizi"
,"Herr khogyani saidkarim"
,"Herr Niamatullah Qeyami"
,"Frau Fatima Rahimzada"
,"Frau KHATRA HOSSAINI"
,"Frau Noorzia Begom"
,"Frau Sahar Kohistani"
,"Frau Arezo Elham"
,"Herr BAKHTEARI MOJTABA"
,"Frau OLWEY BIBI ZAINULARAB"
,"Herr RADFAR FARID AHMAD"
,"Herr RADMANESH MOHAMMAD BAHRAM"
,"Frau Fereshta Hashemi"
,"Frau Farida Omid Afzalpoor"
,"Frau Massouda Zahid"
,"Herr Ahmad Massoud Zahid"
,"Herr Ahmad Jamshid Kohistany"
,"Frau Lina hakimi"
,"Frau Zahra Barekzai"
,"Herr Abdul Ghafar Baraki"
,"Herr MODAQIQ Mahbobullah"
,"Herr ANIS FARID"
,"Herr Hamedi Sayed abdul Moein"
,"Herr Mohammad Jafar Zafari"
,"Herr HUSSAIN KHIL MOHAMMAD AYUB" 
,"Frau Farzana Faqiri"
,"Herr Nisar Baser Ahmad" 
,"Herr Mohammad Asef Salimi"
,"Herr Abdul ghani safi"
,"Herr Saifuddinf Faqiri"
,"Herr Herr Wahid Ahmad noor"
,"Herr AHMADI SHOAIB" 
,"Herr Fazilrahman Saighani"
,"Frau Nasiba Mohammadi"
,"Herr naqibullah saqib"
,"Frau Parisa Arifi"
,"Herr Hamidullah Wahidi"
,"Herr Saleh Abdul Rahman"
,"Herr Abdul Jalil Yousefi" 
,"Herr ENAYAT ENAYATULLAH"
,"Herr ASADULLAH-HABIBI"
,"Herr NADEM SAYED WAHID" 
,"Frau HASIBA OMARZAD" 
,"Frau rohina ghiasi"
,"Frau Hadia Timory"
,"Herr OBEHVAL AHMAD ZAHED" 
,"Herr Shamsullah Shirzai"
,"Frau Hamasa Mehri"
,"Herr Poya Golaqa"
,"Herr Farshid. Ahmad Ramin" 
,"Herr Hikmat Wais Ahmad" 
,"Frau Parisa Arifi"
,"Frau Hosai Naser"
,"Herr Tahiri Alias"
,"Herr SHIRZAD Khalid"
,"Herr MHAMMAD HAKIM HAKIMI"
,"Herr RASEKH NAWABI"
,"Frau Sara Sultani"
,"Frau Sediqa Sultani"
,"Frau Arezo Shirin Sokhan"
,"Frau Momena Muslim"
,"Herr Mohammad Haroon Ayoobi"
,"Herr waheed"
,"Herr SHARIFI MAHDI"
,"Frau HEJRIA ZAHRA"
,"Herr JOYA EZATULLAH"
,"Frau MOHAMMADI NOORIA"
,"Frau INSAF AMIRI ZOHAL"
,"Heer Ahmadi Samiullah"
,"Herr SAMADI AHMAD BASIR"
,"Herr Hasina Hazem"
,"Frau AZIZI WAHIDA"
,"Frau Shamail Tawana"
,"Herr KHURAMI MAWLUDDIN"
,"Herr Pamir Mirzada"
,"Frau Sayeeda Khanum"
,"Herr Abdul saaboor"
,"Herr Salik Mohammad Dawood"
,"HERR AYOOBI MOHAMMAD HAROON"
,"Herr Farshid. Ahmad Ramin"
,"Herr Hariva Fahim" 
,"Herr Sayed Ali Akbary"
,"Herr SHIRZAD OMID"
,"Herr Mohammadi Mohammad zia"
,"Herr YOUSUFI HASSIBULLAH "
,"Frau massouda zahid"
,"Herr Said Jamil Faqiri" 
,"Frau Farida Mohib"
,"Herr Haidari Safiullah" 
,"Herr SHAFAQ MOHAMMAD YONUS" 
,"Herr Sangar Abdul Qaher" 
,"Herr mohammad hussain shirzad"
,"Herr Asadullah Zamari" 
,"Herr HABIBI HABIBULLAH" 
,"Frau Benafsha Bahar Sana"
,"Herr Mohammadi Mohammad zia"
,"Frau HASANI Somaya"
,"Herr Mosleh Hikmatullah" 
,"Herr MOHAMMADI NAWEED "
,"Herr Rohullah Danish"
,"Herr Danesh Seddiq"
,"Herr Saidi Zakirullah "
,"Herr PANAH MOHAMMAD ANIS "
,"Herr Karimi Danial" 
,"Herr RAHIM MOHAMMAD KARIM"
,"Frau Husnia Sadat" 
,"Frau. HAQIQI FRESHTA" 
,"Frau sodaba infomation" 
,"Herr Karimi Maziar "
,"Herr Waheedullah omery"
,"Herr Hamidi Iraj "
,"Frau NOORI Khadija"
,"Herr Ahmad Yaser Safvan"
,"Herr Rezaie Najibullah "
,"Herr Sadat Mir Nazir Hussain" 
,"Herr Majari Merajudin"
,"Frau NAIBI Alia"
,"Herr Alia Naibi" 
,"Herr Mohammadi Fatima"
,"Frau Mohammad Yassin Hussaini" 
,"Herr Abdul Wasi Faramarz"
,"Herr Haidari Firooz Ahmad" 
,"Herr Mayar Qais" 
,"Herr HABIBI AHMAD FAHIM" 
,"Herr Akbari Amir Mirwais" 
,"Frau Zirak Nasima"
,"Herr Azmatullah shaheen"
,"Frau AMIRY Astoray "
,"Herr Raz Mohammad Miazada"
,"Herr Ghulam Qader" 
,"Frau Faiza"
,"Herr zemrai Danish Nazari"
,"Frau Shams Tahereh"
,"Frau Nazifa Mohammadi" 
,"Herr Hamidi Qodratuulah"
,"Frau Maryam Niazi"
,"Herr MOHAMMAD YOUNIS RAHNAWARD"
,"Frau Rahimi Fawzia"
,"Frau Naz Boo Bader"
,"HERR , JALALI MOHAMMAD YAQOOB"
,"Frau Khushbo Ghafari"
,"Herr HABIB WAHIDULLAH"
,"Herr Mohammad Reza NASIRI"
];


function suchung() {
    if (liste.includes(document.querySelector("#username").value)) {
        document.querySelector("#ausgabe").innerHTML = "نام شما در لیست میباشد";
    } else {
        document.querySelector("#ausgabe").innerHTML = "نام شما در لیست موجود نمیباشد";
    };
};
suchung(checkUser);